language: node_js
node_js:
  - 'lts/carbon'  #8.x  - Maintenance LTS
  - 'lts/*'       #10.x - Active LTS
  - 'stable'      #12.x - Current Release
before_install:
  - '[[ `npm --version` =~ ^[1-5]\. ]] && npm i -g npm@latest'
install:
  - npm ci
script:
  - npm run build
  - npm t
